name: navigation
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../core
  core_ui:
    path: ../core_ui

  dashboard:
    path: ../features/dashboard
  character_list:
    path: ../features/character_list
  favorites:
    path: ../features/favorites

  auto_route: ^9.2.2

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.8