name: medications
description: plug feature
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../../core
  domain:
    path: ../../domain
  core_ui:
    path: ../../core_ui
  navigation:
    path: ../../navigation

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.1.7
  mocktail: ^1.0.4

  auto_route_generator: ^9.0.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true